cloudflare_prod_email = "accounts-infra@fakerco.cz"
cloudflare_prod_token = "xxx"
cloudflare_dev_email = "accounts-infra-dev@fakerco.cz"
cloudflare_dev_token = "xxx"
digitalocean_prod_token = "xxx"
digitalocean_dev_token = "xxx"
